// examples/vue-nuxt/app/components/DummyContent.vue
<template>
  <section>
    <h2>Dummy text to make the content scrollable</h2>
    <p>
      Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis eget nisi ut
      velit fermentum ornare. Ut ullamcorper mi id orci malesuada, sed fringilla
      orci pharetra. Sed nec iaculis felis. Sed in auctor enim. Aenean rhoncus,
      nulla nec finibus auctor, lacus magna placerat arcu, pellentesque
      consectetur lacus lectus ut quam. Donec eget suscipit ligula. Mauris vel
      bibendum sapien. Praesent varius magna lacinia sapien facilisis tristique.
      Nulla sit amet felis fermentum, condimentum magna at, elementum purus.
    </p>
    <p>
      Suspendisse eget suscipit ipsum, eget auctor velit. Vestibulum nec ipsum
      placerat, dictum tellus pharetra, ornare massa. Integer posuere augue a
      justo egestas tincidunt. Ut cursus bibendum lorem sed lobortis. Nam nec
      aliquet dui. Maecenas dictum auctor tellus quis placerat. Etiam ac diam ac
      urna vestibulum maximus. Proin luctus elit molestie, hendrerit elit et,
      sodales diam. Pellentesque ipsum tellus, dapibus sit amet cursus et,
      ultricies ut erat. Proin sodales ipsum vitae volutpat lacinia. Nulla
      facilisi.
    </p>
    <p>
      Nunc bibendum dolor viverra tortor euismod, nec ultricies urna tempor.
      Mauris suscipit non risus id maximus. Integer facilisis ligula lacus. In
      eu mi at neque dapibus fringilla ac eget dui. Aenean tincidunt ex non orci
      malesuada tincidunt. Pellentesque ullamcorper vitae purus a bibendum. Nunc
      eget orci gravida, eleifend risus et, commodo est. Phasellus facilisis ex
      eu odio ultrices, vel ultrices eros accumsan. Nam blandit facilisis erat,
      quis tristique ante ultrices eget. Integer malesuada dictum leo, non
      venenatis ipsum convallis at.
    </p>
    <p>
      Nunc mauris felis, placerat a eros vitae, eleifend tristique nisl. Vivamus
      nec pharetra mi. Etiam nec dictum sem, pulvinar cursus nisl. Fusce finibus
      viverra ante. Fusce eros lorem, hendrerit ac iaculis faucibus, tempus sed
      tortor. Vestibulum iaculis nisl nec neque tristique, id porta nunc tempor.
      Cras sed bibendum lectus, in interdum nisi. Nam vel ex in lorem lacinia
      lacinia.
    </p>
    <p>
      Aliquam volutpat nulla purus, ac tristique elit ornare at. Sed semper
      faucibus tellus nec tempor. Curabitur euismod lectus non ultricies
      ultricies. Etiam gravida sodales odio, non lacinia neque rutrum vel. Morbi
      imperdiet risus sed dapibus ullamcorper. Nullam feugiat eleifend
      tincidunt. Class aptent taciti sociosqu ad litora torquent per conubia
      nostra, per inceptos himenaeos. Etiam et libero condimentum, dignissim
      ipsum at, placerat magna. Quisque porttitor pretium ligula, sed pulvinar
      leo commodo ac. Sed semper, eros ut ultricies consequat, erat dui
      fringilla justo, nec cursus turpis justo non lacus. Cras maximus odio
      massa, sit amet efficitur neque ornare a. Ut euismod porta ante, eleifend
      fermentum nulla congue sed. Quisque efficitur, risus at mollis dapibus,
      ligula neque porta ante, in sollicitudin tortor justo vitae nisl. Praesent
      et nulla ac velit iaculis semper eget ut ante.
    </p>
  </section>
</template>

// examples/react-nextjs/components/DummyContent.tsx
export default function DummyContent() {
  return (
    <section>
      <h2>Dummy text to make the content scrollable</h2>
      <p>
        Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis eget nisi
        ut velit fermentum ornare. Ut ullamcorper mi id orci malesuada, sed
        fringilla orci pharetra. Sed nec iaculis felis. Sed in auctor enim.
        Aenean rhoncus, nulla nec finibus auctor, lacus magna placerat arcu,
        pellentesque consectetur lacus lectus ut quam. Donec eget suscipit
        ligula. Mauris vel bibendum sapien. Praesent varius magna lacinia sapien
        facilisis tristique. Nulla sit amet felis fermentum, condimentum magna
        at, elementum purus.
      </p>
      <p>
        Suspendisse eget suscipit ipsum, eget auctor velit. Vestibulum nec ipsum
        placerat, dictum tellus pharetra, ornare massa. Integer posuere augue a
        justo egestas tincidunt. Ut cursus bibendum lorem sed lobortis. Nam nec
        aliquet dui. Maecenas dictum auctor tellus quis placerat. Etiam ac diam
        ac urna vestibulum maximus. Proin luctus elit molestie, hendrerit elit
        et, sodales diam. Pellentesque ipsum tellus, dapibus sit amet cursus et,
        ultricies ut erat. Proin sodales ipsum vitae volutpat lacinia. Nulla
        facilisi.
      </p>
      <p>
        Nunc bibendum dolor viverra tortor euismod, nec ultricies urna tempor.
        Mauris suscipit non risus id maximus. Integer facilisis ligula lacus. In
        eu mi at neque dapibus fringilla ac eget dui. Aenean tincidunt ex non
        orci malesuada tincidunt. Pellentesque ullamcorper vitae purus a
        bibendum. Nunc eget orci gravida, eleifend risus et, commodo est.
        Phasellus facilisis ex eu odio ultrices, vel ultrices eros accumsan. Nam
        blandit facilisis erat, quis tristique ante ultrices eget. Integer
        malesuada dictum leo, non venenatis ipsum convallis at.
      </p>
      <p>
        Nunc mauris felis, placerat a eros vitae, eleifend tristique nisl.
        Vivamus nec pharetra mi. Etiam nec dictum sem, pulvinar cursus nisl.
        Fusce finibus viverra ante. Fusce eros lorem, hendrerit ac iaculis
        faucibus, tempus sed tortor. Vestibulum iaculis nisl nec neque
        tristique, id porta nunc tempor. Cras sed bibendum lectus, in interdum
        nisi. Nam vel ex in lorem lacinia lacinia.
      </p>
      <p>
        Aliquam volutpat nulla purus, ac tristique elit ornare at. Sed semper
        faucibus tellus nec tempor. Curabitur euismod lectus non ultricies
        ultricies. Etiam gravida sodales odio, non lacinia neque rutrum vel.
        Morbi imperdiet risus sed dapibus ullamcorper. Nullam feugiat eleifend
        tincidunt. Class aptent taciti sociosqu ad litora torquent per conubia
        nostra, per inceptos himenaeos. Etiam et libero condimentum, dignissim
        ipsum at, placerat magna. Quisque porttitor pretium ligula, sed pulvinar
        leo commodo ac. Sed semper, eros ut ultricies consequat, erat dui
        fringilla justo, nec cursus turpis justo non lacus. Cras maximus odio
        massa, sit amet efficitur neque ornare a. Ut euismod porta ante,
        eleifend fermentum nulla congue sed. Quisque efficitur, risus at mollis
        dapibus, ligula neque porta ante, in sollicitudin tortor justo vitae
        nisl. Praesent et nulla ac velit iaculis semper eget ut ante.
      </p>
    </section>
  );
}
